/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TnButton {
        "label": string;
        "loading": boolean;
    }
    interface TnTextField {
        "placeholder": string;
        "value": string;
    }
}
export interface TnTextFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTnTextFieldElement;
}
declare global {
    interface HTMLTnButtonElement extends Components.TnButton, HTMLStencilElement {
    }
    var HTMLTnButtonElement: {
        prototype: HTMLTnButtonElement;
        new (): HTMLTnButtonElement;
    };
    interface HTMLTnTextFieldElement extends Components.TnTextField, HTMLStencilElement {
    }
    var HTMLTnTextFieldElement: {
        prototype: HTMLTnTextFieldElement;
        new (): HTMLTnTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "tn-button": HTMLTnButtonElement;
        "tn-text-field": HTMLTnTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface TnButton {
        "label"?: string;
        "loading"?: boolean;
    }
    interface TnTextField {
        "onChange"?: (event: TnTextFieldCustomEvent<string>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "tn-button": TnButton;
        "tn-text-field": TnTextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tn-button": LocalJSX.TnButton & JSXBase.HTMLAttributes<HTMLTnButtonElement>;
            "tn-text-field": LocalJSX.TnTextField & JSXBase.HTMLAttributes<HTMLTnTextFieldElement>;
        }
    }
}
